#!/usr/bin/env bash
# Auto-generated by generate_question_spec_markdown.py
# Processes all question-spec install files in order.
#
# Usage: bash run_all.sh [--url <platform_url>] [--server <view_server>]
#                        [--userid <user_id>] [--user_pass <user_pwd>]

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Pass through any arguments to dr_egeria
ARGS="$@"

echo "Processing 00_perspectives.md..."
dr_egeria "${SCRIPT_DIR}/00_perspectives.md" --process $ARGS
echo "Done."

echo "Processing Actor-Profiles.md..."
dr_egeria "${SCRIPT_DIR}/Actor-Profiles.md" --process $ARGS
echo "Done."

echo "Processing Actor-Profiles-Assigned-MD.md..."
dr_egeria "${SCRIPT_DIR}/Actor-Profiles-Assigned-MD.md" --process $ARGS
echo "Done."

echo "Processing Actor-Roles.md..."
dr_egeria "${SCRIPT_DIR}/Actor-Roles.md" --process $ARGS
echo "Done."

echo "Processing Agreements.md..."
dr_egeria "${SCRIPT_DIR}/Agreements.md" --process $ARGS
echo "Done."

echo "Processing Asset-Graph.md..."
dr_egeria "${SCRIPT_DIR}/Asset-Graph.md" --process $ARGS
echo "Done."

echo "Processing Asset-Types.md..."
dr_egeria "${SCRIPT_DIR}/Asset-Types.md" --process $ARGS
echo "Done."

echo "Processing BasicCollections.md..."
dr_egeria "${SCRIPT_DIR}/BasicCollections.md" --process $ARGS
echo "Done."

echo "Processing BusinessCapabilities.md..."
dr_egeria "${SCRIPT_DIR}/BusinessCapabilities.md" --process $ARGS
echo "Done."

echo "Processing Catalog-Target.md..."
dr_egeria "${SCRIPT_DIR}/Catalog-Target.md" --process $ARGS
echo "Done."

echo "Processing CitedDocument.md..."
dr_egeria "${SCRIPT_DIR}/CitedDocument.md" --process $ARGS
echo "Done."

echo "Processing Collection_Members.md..."
dr_egeria "${SCRIPT_DIR}/Collection_Members.md" --process $ARGS
echo "Done."

echo "Processing Collection-MindMap.md..."
dr_egeria "${SCRIPT_DIR}/Collection-MindMap.md" --process $ARGS
echo "Done."

echo "Processing Collections.md..."
dr_egeria "${SCRIPT_DIR}/Collections.md" --process $ARGS
echo "Done."

echo "Processing Data-Classes.md..."
dr_egeria "${SCRIPT_DIR}/Data-Classes.md" --process $ARGS
echo "Done."

echo "Processing Data-Dictionaries.md..."
dr_egeria "${SCRIPT_DIR}/Data-Dictionaries.md" --process $ARGS
echo "Done."

echo "Processing Data-Fields.md..."
dr_egeria "${SCRIPT_DIR}/Data-Fields.md" --process $ARGS
echo "Done."

echo "Processing Data-Specifications.md..."
dr_egeria "${SCRIPT_DIR}/Data-Specifications.md" --process $ARGS
echo "Done."

echo "Processing Data-Structures.md..."
dr_egeria "${SCRIPT_DIR}/Data-Structures.md" --process $ARGS
echo "Done."

echo "Processing Data-Value-Spec.md..."
dr_egeria "${SCRIPT_DIR}/Data-Value-Spec.md" --process $ARGS
echo "Done."

echo "Processing Default.md..."
dr_egeria "${SCRIPT_DIR}/Default.md" --process $ARGS
echo "Done."

echo "Processing Digital-Product-Catalog.md..."
dr_egeria "${SCRIPT_DIR}/Digital-Product-Catalog.md" --process $ARGS
echo "Done."

echo "Processing Digital-Product-Catalog-MyE.md..."
dr_egeria "${SCRIPT_DIR}/Digital-Product-Catalog-MyE.md" --process $ARGS
echo "Done."

echo "Processing Digital-Products.md..."
dr_egeria "${SCRIPT_DIR}/Digital-Products.md" --process $ARGS
echo "Done."

echo "Processing Digital-Products-MyE.md..."
dr_egeria "${SCRIPT_DIR}/Digital-Products-MyE.md" --process $ARGS
echo "Done."

echo "Processing Digital-Products-Slim.md..."
dr_egeria "${SCRIPT_DIR}/Digital-Products-Slim.md" --process $ARGS
echo "Done."

echo "Processing Element-By-Owner.md..."
dr_egeria "${SCRIPT_DIR}/Element-By-Owner.md" --process $ARGS
echo "Done."

echo "Processing Engine-Actions.md..."
dr_egeria "${SCRIPT_DIR}/Engine-Actions.md" --process $ARGS
echo "Done."

echo "Processing External-References.md..."
dr_egeria "${SCRIPT_DIR}/External-References.md" --process $ARGS
echo "Done."

echo "Processing ExternalReference.md..."
dr_egeria "${SCRIPT_DIR}/ExternalReference.md" --process $ARGS
echo "Done."

echo "Processing Folders.md..."
dr_egeria "${SCRIPT_DIR}/Folders.md" --process $ARGS
echo "Done."

echo "Processing Glossaries.md..."
dr_egeria "${SCRIPT_DIR}/Glossaries.md" --process $ARGS
echo "Done."

echo "Processing Glossary-Terms.md..."
dr_egeria "${SCRIPT_DIR}/Glossary-Terms.md" --process $ARGS
echo "Done."

echo "Processing Governance_Basics.md..."
dr_egeria "${SCRIPT_DIR}/Governance_Basics.md" --process $ARGS
echo "Done."

echo "Processing Governance_Def.md..."
dr_egeria "${SCRIPT_DIR}/Governance_Def.md" --process $ARGS
echo "Done."

echo "Processing Governance_Definitions.md..."
dr_egeria "${SCRIPT_DIR}/Governance_Definitions.md" --process $ARGS
echo "Done."

echo "Processing Governance_Policies.md..."
dr_egeria "${SCRIPT_DIR}/Governance_Policies.md" --process $ARGS
echo "Done."

echo "Processing Governance-Controls.md..."
dr_egeria "${SCRIPT_DIR}/Governance-Controls.md" --process $ARGS
echo "Done."

echo "Processing Governance-Process.md..."
dr_egeria "${SCRIPT_DIR}/Governance-Process.md" --process $ARGS
echo "Done."

echo "Processing Governance-Zone-Overview-Charts.md..."
dr_egeria "${SCRIPT_DIR}/Governance-Zone-Overview-Charts.md" --process $ARGS
echo "Done."

echo "Processing Governance-Zones.md..."
dr_egeria "${SCRIPT_DIR}/Governance-Zones.md" --process $ARGS
echo "Done."

echo "Processing Help-Terms.md..."
dr_egeria "${SCRIPT_DIR}/Help-Terms.md" --process $ARGS
echo "Done."

echo "Processing Informal-Tags-DrE.md..."
dr_egeria "${SCRIPT_DIR}/Informal-Tags-DrE.md" --process $ARGS
echo "Done."

echo "Processing IntegrationConnectors.md..."
dr_egeria "${SCRIPT_DIR}/IntegrationConnectors.md" --process $ARGS
echo "Done."

echo "Processing Journal-Entry-DrE.md..."
dr_egeria "${SCRIPT_DIR}/Journal-Entry-DrE.md" --process $ARGS
echo "Done."

echo "Processing License-Type.md..."
dr_egeria "${SCRIPT_DIR}/License-Type.md" --process $ARGS
echo "Done."

echo "Processing My-User.md..."
dr_egeria "${SCRIPT_DIR}/My-User.md" --process $ARGS
echo "Done."

echo "Processing My-User-Activities.md..."
dr_egeria "${SCRIPT_DIR}/My-User-Activities.md" --process $ARGS
echo "Done."

echo "Processing My-User-Blogs.md..."
dr_egeria "${SCRIPT_DIR}/My-User-Blogs.md" --process $ARGS
echo "Done."

echo "Processing My-User-Journals.md..."
dr_egeria "${SCRIPT_DIR}/My-User-Journals.md" --process $ARGS
echo "Done."

echo "Processing My-User-MD.md..."
dr_egeria "${SCRIPT_DIR}/My-User-MD.md" --process $ARGS
echo "Done."

echo "Processing My-User-ToDos.md..."
dr_egeria "${SCRIPT_DIR}/My-User-ToDos.md" --process $ARGS
echo "Done."

echo "Processing OMAGServers.md..."
dr_egeria "${SCRIPT_DIR}/OMAGServers.md" --process $ARGS
echo "Done."

echo "Processing Org-Chart.md..."
dr_egeria "${SCRIPT_DIR}/Org-Chart.md" --process $ARGS
echo "Done."

echo "Processing Perspectives.md..."
dr_egeria "${SCRIPT_DIR}/Perspectives.md" --process $ARGS
echo "Done."

echo "Processing Platforms.md..."
dr_egeria "${SCRIPT_DIR}/Platforms.md" --process $ARGS
echo "Done."

echo "Processing Projects.md..."
dr_egeria "${SCRIPT_DIR}/Projects.md" --process $ARGS
echo "Done."

echo "Processing Referenceable.md..."
dr_egeria "${SCRIPT_DIR}/Referenceable.md" --process $ARGS
echo "Done."

echo "Processing Registered-Services.md..."
dr_egeria "${SCRIPT_DIR}/Registered-Services.md" --process $ARGS
echo "Done."

echo "Processing RelatedMedia.md..."
dr_egeria "${SCRIPT_DIR}/RelatedMedia.md" --process $ARGS
echo "Done."

echo "Processing Search-Keywords.md..."
dr_egeria "${SCRIPT_DIR}/Search-Keywords.md" --process $ARGS
echo "Done."

echo "Processing Secrets-Collection-User-Profile-Charts.md..."
dr_egeria "${SCRIPT_DIR}/Secrets-Collection-User-Profile-Charts.md" --process $ARGS
echo "Done."

echo "Processing Severity-Definitions.md..."
dr_egeria "${SCRIPT_DIR}/Severity-Definitions.md" --process $ARGS
echo "Done."

echo "Processing Skills.md..."
dr_egeria "${SCRIPT_DIR}/Skills.md" --process $ARGS
echo "Done."

echo "Processing Solution-Blueprint.md..."
dr_egeria "${SCRIPT_DIR}/Solution-Blueprint.md" --process $ARGS
echo "Done."

echo "Processing Team-Members.md..."
dr_egeria "${SCRIPT_DIR}/Team-Members.md" --process $ARGS
echo "Done."

echo "Processing Tech-Type-Details.md..."
dr_egeria "${SCRIPT_DIR}/Tech-Type-Details.md" --process $ARGS
echo "Done."

echo "Processing Tech-Type-Details-MD.md..."
dr_egeria "${SCRIPT_DIR}/Tech-Type-Details-MD.md" --process $ARGS
echo "Done."

echo "Processing Tech-Type-Elements.md..."
dr_egeria "${SCRIPT_DIR}/Tech-Type-Elements.md" --process $ARGS
echo "Done."

echo "Processing Tech-Type-Processes.md..."
dr_egeria "${SCRIPT_DIR}/Tech-Type-Processes.md" --process $ARGS
echo "Done."

echo "Processing Tech-Types.md..."
dr_egeria "${SCRIPT_DIR}/Tech-Types.md" --process $ARGS
echo "Done."

echo "Processing TypeDef.md..."
dr_egeria "${SCRIPT_DIR}/TypeDef.md" --process $ARGS
echo "Done."

echo "Processing User-Identities.md..."
dr_egeria "${SCRIPT_DIR}/User-Identities.md" --process $ARGS
echo "Done."

echo "Processing Valid-Value-Def.md..."
dr_egeria "${SCRIPT_DIR}/Valid-Value-Def.md" --process $ARGS
echo "Done."

echo "Processing Valid-Values.md..."
dr_egeria "${SCRIPT_DIR}/Valid-Values.md" --process $ARGS
echo "Done."

echo "Processing Developer-Questions.md..."
dr_egeria "${SCRIPT_DIR}/Developer-Questions.md" --process $ARGS
echo "Done."

